name: 'Run integration tests'

on:
  pull_request_target:
    types: [opened, reopened]
    branches:
      - catty-reminders-app

permissions:
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Print Workflow Dispatch Inputs and Env Vars
        uses: shayki5/print-workflow-dispatch-inputs@v1
        with:
          add_to_summary: 'true'

      - name: Resolve assignment check
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $TITLE"

          if [[ "$TITLE" == *"Лаб.1"* ]]; then
            echo "ASSIGNMENT_CHECK=webhooks_devops_assignment" >> $GITHUB_ENV
          elif [[ "$TITLE" == *"Лаб.2"* ]]; then
            echo "ASSIGNMENT_CHECK=github_actions_assignment" >> $GITHUB_ENV
          elif [[ "$TITLE" == *"Лаб.3"* ]]; then
            echo "ASSIGNMENT_CHECK=docker_assignment" >> $GITHUB_ENV
          elif [[ "$TITLE" == *"Лаб.4"* ]]; then
            echo "ASSIGNMENT_CHECK=compose_assignment" >> $GITHUB_ENV
          else
            echo "❌ PR title does not contain a valid lab identifier (Лаб.1–Лаб.4)"
            exit 1
          fi

      - name: Run check for webhooks_devops_assignment
        if:  env.ASSIGNMENT_CHECK == 'webhooks_devops_assignment'
        uses: prafdin/check-assignment@main
        with:
          params_file: 'params.json'
          assignee_login: ${{ github.event.pull_request.user.login }}
          repo_name: ${{ github.event.pull_request.head.repo.full_name }}
          sa_ssh_pkey: ${{ secrets.SSH_PRIVATE_KEY }}
          branch_name: ${{ github.event.pull_request.head.ref }}
          webhooks_devops_assignment: true

      - name: Run check for github_actions_assignment
        if:  env.ASSIGNMENT_CHECK == 'webhooks_devops_assignment'
        uses: prafdin/check-assignment@main
        with:
          params_file: 'params.json'
          assignee_login: ${{ github.event.pull_request.user.login }}
          repo_name: ${{ github.event.pull_request.head.repo.full_name }}
          sa_ssh_pkey: ${{ secrets.SSH_PRIVATE_KEY }}
          branch_name: ${{ github.event.pull_request.head.ref }}
          github_token: ${{ secrets.SA_GITHUB_TOKEN }}
          github_actions_assignment: true

      - name: Run check for docker_assignment
        if:  env.ASSIGNMENT_CHECK == 'docker_assignment'
        uses: prafdin/check-assignment@main
        with:
          params_file: 'params.json'
          assignee_login: ${{ github.event.pull_request.user.login }}
          repo_name: ${{ github.event.pull_request.head.repo.full_name }}
          sa_ssh_pkey: ${{ secrets.SSH_PRIVATE_KEY }}
          branch_name: ${{ github.event.pull_request.head.ref }}
          github_token: ${{ secrets.SA_GITHUB_TOKEN }}
          docker_assignment: true

      - name: Run check for compose_assignment
        if:  env.ASSIGNMENT_CHECK == 'compose_assignment'
        uses: prafdin/check-assignment@main
        with:
          params_file: 'params.json'
          assignee_login: ${{ github.event.pull_request.user.login }}
          repo_name: ${{ github.event.pull_request.head.repo.full_name }}
          sa_ssh_pkey: ${{ secrets.SSH_PRIVATE_KEY }}
          branch_name: ${{ github.event.pull_request.head.ref }}
          github_token: ${{ secrets.SA_GITHUB_TOKEN }}
          compose_assignment: true
